/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db;


import cn.com.ho.workflow.infrastructure.db.tables.ActEvtLog;
import cn.com.ho.workflow.infrastructure.db.tables.ActGeBytearray;
import cn.com.ho.workflow.infrastructure.db.tables.ActGeProperty;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiActinst;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiAttachment;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiComment;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiDetail;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiIdentitylink;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiProcinst;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiTaskinst;
import cn.com.ho.workflow.infrastructure.db.tables.ActHiVarinst;
import cn.com.ho.workflow.infrastructure.db.tables.ActProcdefInfo;
import cn.com.ho.workflow.infrastructure.db.tables.ActReDeployment;
import cn.com.ho.workflow.infrastructure.db.tables.ActReModel;
import cn.com.ho.workflow.infrastructure.db.tables.ActReProcdef;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuDeadletterJob;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuEventSubscr;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuExecution;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuIdentitylink;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuIntegration;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuJob;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuSuspendedJob;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuTask;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuTimerJob;
import cn.com.ho.workflow.infrastructure.db.tables.ActRuVariable;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfCountersign;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfForm;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfListener;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfNode;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfNotice;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfOperation;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfRule;
import cn.com.ho.workflow.infrastructure.db.tables.BpmConfUser;
import cn.com.ho.workflow.infrastructure.db.tables.DtsPostgresHeartbeat;
import cn.com.ho.workflow.infrastructure.db.tables.TPProcDefXml;
import cn.com.ho.workflow.infrastructure.db.tables.TPProcess;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workflow extends SchemaImpl {

    private static final long serialVersionUID = 1631867281;

    /**
     * The reference instance of <code>workflow</code>
     */
    public static final Workflow WORKFLOW = new Workflow();

    /**
     * The table <code>workflow.act_evt_log</code>.
     */
    public final ActEvtLog ACT_EVT_LOG = cn.com.ho.workflow.infrastructure.db.tables.ActEvtLog.ACT_EVT_LOG;

    /**
     * The table <code>workflow.act_ge_bytearray</code>.
     */
    public final ActGeBytearray ACT_GE_BYTEARRAY = cn.com.ho.workflow.infrastructure.db.tables.ActGeBytearray.ACT_GE_BYTEARRAY;

    /**
     * The table <code>workflow.act_ge_property</code>.
     */
    public final ActGeProperty ACT_GE_PROPERTY = cn.com.ho.workflow.infrastructure.db.tables.ActGeProperty.ACT_GE_PROPERTY;

    /**
     * The table <code>workflow.act_hi_actinst</code>.
     */
    public final ActHiActinst ACT_HI_ACTINST = cn.com.ho.workflow.infrastructure.db.tables.ActHiActinst.ACT_HI_ACTINST;

    /**
     * The table <code>workflow.act_hi_attachment</code>.
     */
    public final ActHiAttachment ACT_HI_ATTACHMENT = cn.com.ho.workflow.infrastructure.db.tables.ActHiAttachment.ACT_HI_ATTACHMENT;

    /**
     * The table <code>workflow.act_hi_comment</code>.
     */
    public final ActHiComment ACT_HI_COMMENT = cn.com.ho.workflow.infrastructure.db.tables.ActHiComment.ACT_HI_COMMENT;

    /**
     * The table <code>workflow.act_hi_detail</code>.
     */
    public final ActHiDetail ACT_HI_DETAIL = cn.com.ho.workflow.infrastructure.db.tables.ActHiDetail.ACT_HI_DETAIL;

    /**
     * The table <code>workflow.act_hi_identitylink</code>.
     */
    public final ActHiIdentitylink ACT_HI_IDENTITYLINK = cn.com.ho.workflow.infrastructure.db.tables.ActHiIdentitylink.ACT_HI_IDENTITYLINK;

    /**
     * The table <code>workflow.act_hi_procinst</code>.
     */
    public final ActHiProcinst ACT_HI_PROCINST = cn.com.ho.workflow.infrastructure.db.tables.ActHiProcinst.ACT_HI_PROCINST;

    /**
     * The table <code>workflow.act_hi_taskinst</code>.
     */
    public final ActHiTaskinst ACT_HI_TASKINST = cn.com.ho.workflow.infrastructure.db.tables.ActHiTaskinst.ACT_HI_TASKINST;

    /**
     * The table <code>workflow.act_hi_varinst</code>.
     */
    public final ActHiVarinst ACT_HI_VARINST = cn.com.ho.workflow.infrastructure.db.tables.ActHiVarinst.ACT_HI_VARINST;

    /**
     * The table <code>workflow.act_procdef_info</code>.
     */
    public final ActProcdefInfo ACT_PROCDEF_INFO = cn.com.ho.workflow.infrastructure.db.tables.ActProcdefInfo.ACT_PROCDEF_INFO;

    /**
     * The table <code>workflow.act_re_deployment</code>.
     */
    public final ActReDeployment ACT_RE_DEPLOYMENT = cn.com.ho.workflow.infrastructure.db.tables.ActReDeployment.ACT_RE_DEPLOYMENT;

    /**
     * The table <code>workflow.act_re_model</code>.
     */
    public final ActReModel ACT_RE_MODEL = cn.com.ho.workflow.infrastructure.db.tables.ActReModel.ACT_RE_MODEL;

    /**
     * The table <code>workflow.act_re_procdef</code>.
     */
    public final ActReProcdef ACT_RE_PROCDEF = cn.com.ho.workflow.infrastructure.db.tables.ActReProcdef.ACT_RE_PROCDEF;

    /**
     * The table <code>workflow.act_ru_deadletter_job</code>.
     */
    public final ActRuDeadletterJob ACT_RU_DEADLETTER_JOB = cn.com.ho.workflow.infrastructure.db.tables.ActRuDeadletterJob.ACT_RU_DEADLETTER_JOB;

    /**
     * The table <code>workflow.act_ru_event_subscr</code>.
     */
    public final ActRuEventSubscr ACT_RU_EVENT_SUBSCR = cn.com.ho.workflow.infrastructure.db.tables.ActRuEventSubscr.ACT_RU_EVENT_SUBSCR;

    /**
     * The table <code>workflow.act_ru_execution</code>.
     */
    public final ActRuExecution ACT_RU_EXECUTION = cn.com.ho.workflow.infrastructure.db.tables.ActRuExecution.ACT_RU_EXECUTION;

    /**
     * The table <code>workflow.act_ru_identitylink</code>.
     */
    public final ActRuIdentitylink ACT_RU_IDENTITYLINK = cn.com.ho.workflow.infrastructure.db.tables.ActRuIdentitylink.ACT_RU_IDENTITYLINK;

    /**
     * The table <code>workflow.act_ru_integration</code>.
     */
    public final ActRuIntegration ACT_RU_INTEGRATION = cn.com.ho.workflow.infrastructure.db.tables.ActRuIntegration.ACT_RU_INTEGRATION;

    /**
     * The table <code>workflow.act_ru_job</code>.
     */
    public final ActRuJob ACT_RU_JOB = cn.com.ho.workflow.infrastructure.db.tables.ActRuJob.ACT_RU_JOB;

    /**
     * The table <code>workflow.act_ru_suspended_job</code>.
     */
    public final ActRuSuspendedJob ACT_RU_SUSPENDED_JOB = cn.com.ho.workflow.infrastructure.db.tables.ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB;

    /**
     * The table <code>workflow.act_ru_task</code>.
     */
    public final ActRuTask ACT_RU_TASK = cn.com.ho.workflow.infrastructure.db.tables.ActRuTask.ACT_RU_TASK;

    /**
     * The table <code>workflow.act_ru_timer_job</code>.
     */
    public final ActRuTimerJob ACT_RU_TIMER_JOB = cn.com.ho.workflow.infrastructure.db.tables.ActRuTimerJob.ACT_RU_TIMER_JOB;

    /**
     * The table <code>workflow.act_ru_variable</code>.
     */
    public final ActRuVariable ACT_RU_VARIABLE = cn.com.ho.workflow.infrastructure.db.tables.ActRuVariable.ACT_RU_VARIABLE;

    /**
     * The table <code>workflow.bpm_conf_countersign</code>.
     */
    public final BpmConfCountersign BPM_CONF_COUNTERSIGN = cn.com.ho.workflow.infrastructure.db.tables.BpmConfCountersign.BPM_CONF_COUNTERSIGN;

    /**
     * 流程模型设置表单
     */
    public final BpmConfForm BPM_CONF_FORM = cn.com.ho.workflow.infrastructure.db.tables.BpmConfForm.BPM_CONF_FORM;

    /**
     * 流程模型设置监听器
     */
    public final BpmConfListener BPM_CONF_LISTENER = cn.com.ho.workflow.infrastructure.db.tables.BpmConfListener.BPM_CONF_LISTENER;

    /**
     * The table <code>workflow.bpm_conf_node</code>.
     */
    public final BpmConfNode BPM_CONF_NODE = cn.com.ho.workflow.infrastructure.db.tables.BpmConfNode.BPM_CONF_NODE;

    /**
     * 流程模型设置通知
     */
    public final BpmConfNotice BPM_CONF_NOTICE = cn.com.ho.workflow.infrastructure.db.tables.BpmConfNotice.BPM_CONF_NOTICE;

    /**
     * The table <code>workflow.bpm_conf_operation</code>.
     */
    public final BpmConfOperation BPM_CONF_OPERATION = cn.com.ho.workflow.infrastructure.db.tables.BpmConfOperation.BPM_CONF_OPERATION;

    /**
     * The table <code>workflow.bpm_conf_rule</code>.
     */
    public final BpmConfRule BPM_CONF_RULE = cn.com.ho.workflow.infrastructure.db.tables.BpmConfRule.BPM_CONF_RULE;

    /**
     * The table <code>workflow.bpm_conf_user</code>.
     */
    public final BpmConfUser BPM_CONF_USER = cn.com.ho.workflow.infrastructure.db.tables.BpmConfUser.BPM_CONF_USER;

    /**
     * The table <code>workflow.dts_postgres_heartbeat</code>.
     */
    public final DtsPostgresHeartbeat DTS_POSTGRES_HEARTBEAT = cn.com.ho.workflow.infrastructure.db.tables.DtsPostgresHeartbeat.DTS_POSTGRES_HEARTBEAT;

    /**
     * The table <code>workflow.t_p_proc_def_xml</code>.
     */
    public final TPProcDefXml T_P_PROC_DEF_XML = cn.com.ho.workflow.infrastructure.db.tables.TPProcDefXml.T_P_PROC_DEF_XML;

    /**
     * The table <code>workflow.t_p_process</code>.
     */
    public final TPProcess T_P_PROCESS = cn.com.ho.workflow.infrastructure.db.tables.TPProcess.T_P_PROCESS;

    /**
     * No further instances allowed
     */
    private Workflow() {
        super("workflow", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACT_EVT_LOG_LOG_NR__SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ActEvtLog.ACT_EVT_LOG,
            ActGeBytearray.ACT_GE_BYTEARRAY,
            ActGeProperty.ACT_GE_PROPERTY,
            ActHiActinst.ACT_HI_ACTINST,
            ActHiAttachment.ACT_HI_ATTACHMENT,
            ActHiComment.ACT_HI_COMMENT,
            ActHiDetail.ACT_HI_DETAIL,
            ActHiIdentitylink.ACT_HI_IDENTITYLINK,
            ActHiProcinst.ACT_HI_PROCINST,
            ActHiTaskinst.ACT_HI_TASKINST,
            ActHiVarinst.ACT_HI_VARINST,
            ActProcdefInfo.ACT_PROCDEF_INFO,
            ActReDeployment.ACT_RE_DEPLOYMENT,
            ActReModel.ACT_RE_MODEL,
            ActReProcdef.ACT_RE_PROCDEF,
            ActRuDeadletterJob.ACT_RU_DEADLETTER_JOB,
            ActRuEventSubscr.ACT_RU_EVENT_SUBSCR,
            ActRuExecution.ACT_RU_EXECUTION,
            ActRuIdentitylink.ACT_RU_IDENTITYLINK,
            ActRuIntegration.ACT_RU_INTEGRATION,
            ActRuJob.ACT_RU_JOB,
            ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB,
            ActRuTask.ACT_RU_TASK,
            ActRuTimerJob.ACT_RU_TIMER_JOB,
            ActRuVariable.ACT_RU_VARIABLE,
            BpmConfCountersign.BPM_CONF_COUNTERSIGN,
            BpmConfForm.BPM_CONF_FORM,
            BpmConfListener.BPM_CONF_LISTENER,
            BpmConfNode.BPM_CONF_NODE,
            BpmConfNotice.BPM_CONF_NOTICE,
            BpmConfOperation.BPM_CONF_OPERATION,
            BpmConfRule.BPM_CONF_RULE,
            BpmConfUser.BPM_CONF_USER,
            DtsPostgresHeartbeat.DTS_POSTGRES_HEARTBEAT,
            TPProcDefXml.T_P_PROC_DEF_XML,
            TPProcess.T_P_PROCESS);
    }
}
