/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiComment implements Serializable {

    private static final long serialVersionUID = -1431926096;

    private String        id_;
    private String        type_;
    private LocalDateTime time_;
    private String        userId_;
    private String        taskId_;
    private String        procInstId_;
    private String        action_;
    private String        message_;
    private byte[]        fullMsg_;

    public ActHiComment() {}

    public ActHiComment(ActHiComment value) {
        this.id_ = value.id_;
        this.type_ = value.type_;
        this.time_ = value.time_;
        this.userId_ = value.userId_;
        this.taskId_ = value.taskId_;
        this.procInstId_ = value.procInstId_;
        this.action_ = value.action_;
        this.message_ = value.message_;
        this.fullMsg_ = value.fullMsg_;
    }

    public ActHiComment(
        String        id_,
        String        type_,
        LocalDateTime time_,
        String        userId_,
        String        taskId_,
        String        procInstId_,
        String        action_,
        String        message_,
        byte[]        fullMsg_
    ) {
        this.id_ = id_;
        this.type_ = type_;
        this.time_ = time_;
        this.userId_ = userId_;
        this.taskId_ = taskId_;
        this.procInstId_ = procInstId_;
        this.action_ = action_;
        this.message_ = message_;
        this.fullMsg_ = fullMsg_;
    }

    public String getId_() {
        return this.id_;
    }

    public void setId_(String id_) {
        this.id_ = id_;
    }

    public String getType_() {
        return this.type_;
    }

    public void setType_(String type_) {
        this.type_ = type_;
    }

    public LocalDateTime getTime_() {
        return this.time_;
    }

    public void setTime_(LocalDateTime time_) {
        this.time_ = time_;
    }

    public String getUserId_() {
        return this.userId_;
    }

    public void setUserId_(String userId_) {
        this.userId_ = userId_;
    }

    public String getTaskId_() {
        return this.taskId_;
    }

    public void setTaskId_(String taskId_) {
        this.taskId_ = taskId_;
    }

    public String getProcInstId_() {
        return this.procInstId_;
    }

    public void setProcInstId_(String procInstId_) {
        this.procInstId_ = procInstId_;
    }

    public String getAction_() {
        return this.action_;
    }

    public void setAction_(String action_) {
        this.action_ = action_;
    }

    public String getMessage_() {
        return this.message_;
    }

    public void setMessage_(String message_) {
        this.message_ = message_;
    }

    public byte[] getFullMsg_() {
        return this.fullMsg_;
    }

    public void setFullMsg_(byte... fullMsg_) {
        this.fullMsg_ = fullMsg_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActHiComment (");

        sb.append(id_);
        sb.append(", ").append(type_);
        sb.append(", ").append(time_);
        sb.append(", ").append(userId_);
        sb.append(", ").append(taskId_);
        sb.append(", ").append(procInstId_);
        sb.append(", ").append(action_);
        sb.append(", ").append(message_);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
