/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActProcdefInfo implements Serializable {

    private static final long serialVersionUID = 9050643;

    private String  id_;
    private String  procDefId_;
    private Integer rev_;
    private String  infoJsonId_;

    public ActProcdefInfo() {}

    public ActProcdefInfo(ActProcdefInfo value) {
        this.id_ = value.id_;
        this.procDefId_ = value.procDefId_;
        this.rev_ = value.rev_;
        this.infoJsonId_ = value.infoJsonId_;
    }

    public ActProcdefInfo(
        String  id_,
        String  procDefId_,
        Integer rev_,
        String  infoJsonId_
    ) {
        this.id_ = id_;
        this.procDefId_ = procDefId_;
        this.rev_ = rev_;
        this.infoJsonId_ = infoJsonId_;
    }

    public String getId_() {
        return this.id_;
    }

    public void setId_(String id_) {
        this.id_ = id_;
    }

    public String getProcDefId_() {
        return this.procDefId_;
    }

    public void setProcDefId_(String procDefId_) {
        this.procDefId_ = procDefId_;
    }

    public Integer getRev_() {
        return this.rev_;
    }

    public void setRev_(Integer rev_) {
        this.rev_ = rev_;
    }

    public String getInfoJsonId_() {
        return this.infoJsonId_;
    }

    public void setInfoJsonId_(String infoJsonId_) {
        this.infoJsonId_ = infoJsonId_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActProcdefInfo (");

        sb.append(id_);
        sb.append(", ").append(procDefId_);
        sb.append(", ").append(rev_);
        sb.append(", ").append(infoJsonId_);

        sb.append(")");
        return sb.toString();
    }
}
