/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReModel implements Serializable {

    private static final long serialVersionUID = -1725380517;

    private String        id_;
    private Integer       rev_;
    private String        name_;
    private String        key_;
    private String        category_;
    private LocalDateTime createTime_;
    private LocalDateTime lastUpdateTime_;
    private Integer       version_;
    private String        metaInfo_;
    private String        deploymentId_;
    private String        editorSourceValueId_;
    private String        editorSourceExtraValueId_;
    private String        tenantId_;

    public ActReModel() {}

    public ActReModel(ActReModel value) {
        this.id_ = value.id_;
        this.rev_ = value.rev_;
        this.name_ = value.name_;
        this.key_ = value.key_;
        this.category_ = value.category_;
        this.createTime_ = value.createTime_;
        this.lastUpdateTime_ = value.lastUpdateTime_;
        this.version_ = value.version_;
        this.metaInfo_ = value.metaInfo_;
        this.deploymentId_ = value.deploymentId_;
        this.editorSourceValueId_ = value.editorSourceValueId_;
        this.editorSourceExtraValueId_ = value.editorSourceExtraValueId_;
        this.tenantId_ = value.tenantId_;
    }

    public ActReModel(
        String        id_,
        Integer       rev_,
        String        name_,
        String        key_,
        String        category_,
        LocalDateTime createTime_,
        LocalDateTime lastUpdateTime_,
        Integer       version_,
        String        metaInfo_,
        String        deploymentId_,
        String        editorSourceValueId_,
        String        editorSourceExtraValueId_,
        String        tenantId_
    ) {
        this.id_ = id_;
        this.rev_ = rev_;
        this.name_ = name_;
        this.key_ = key_;
        this.category_ = category_;
        this.createTime_ = createTime_;
        this.lastUpdateTime_ = lastUpdateTime_;
        this.version_ = version_;
        this.metaInfo_ = metaInfo_;
        this.deploymentId_ = deploymentId_;
        this.editorSourceValueId_ = editorSourceValueId_;
        this.editorSourceExtraValueId_ = editorSourceExtraValueId_;
        this.tenantId_ = tenantId_;
    }

    public String getId_() {
        return this.id_;
    }

    public void setId_(String id_) {
        this.id_ = id_;
    }

    public Integer getRev_() {
        return this.rev_;
    }

    public void setRev_(Integer rev_) {
        this.rev_ = rev_;
    }

    public String getName_() {
        return this.name_;
    }

    public void setName_(String name_) {
        this.name_ = name_;
    }

    public String getKey_() {
        return this.key_;
    }

    public void setKey_(String key_) {
        this.key_ = key_;
    }

    public String getCategory_() {
        return this.category_;
    }

    public void setCategory_(String category_) {
        this.category_ = category_;
    }

    public LocalDateTime getCreateTime_() {
        return this.createTime_;
    }

    public void setCreateTime_(LocalDateTime createTime_) {
        this.createTime_ = createTime_;
    }

    public LocalDateTime getLastUpdateTime_() {
        return this.lastUpdateTime_;
    }

    public void setLastUpdateTime_(LocalDateTime lastUpdateTime_) {
        this.lastUpdateTime_ = lastUpdateTime_;
    }

    public Integer getVersion_() {
        return this.version_;
    }

    public void setVersion_(Integer version_) {
        this.version_ = version_;
    }

    public String getMetaInfo_() {
        return this.metaInfo_;
    }

    public void setMetaInfo_(String metaInfo_) {
        this.metaInfo_ = metaInfo_;
    }

    public String getDeploymentId_() {
        return this.deploymentId_;
    }

    public void setDeploymentId_(String deploymentId_) {
        this.deploymentId_ = deploymentId_;
    }

    public String getEditorSourceValueId_() {
        return this.editorSourceValueId_;
    }

    public void setEditorSourceValueId_(String editorSourceValueId_) {
        this.editorSourceValueId_ = editorSourceValueId_;
    }

    public String getEditorSourceExtraValueId_() {
        return this.editorSourceExtraValueId_;
    }

    public void setEditorSourceExtraValueId_(String editorSourceExtraValueId_) {
        this.editorSourceExtraValueId_ = editorSourceExtraValueId_;
    }

    public String getTenantId_() {
        return this.tenantId_;
    }

    public void setTenantId_(String tenantId_) {
        this.tenantId_ = tenantId_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActReModel (");

        sb.append(id_);
        sb.append(", ").append(rev_);
        sb.append(", ").append(name_);
        sb.append(", ").append(key_);
        sb.append(", ").append(category_);
        sb.append(", ").append(createTime_);
        sb.append(", ").append(lastUpdateTime_);
        sb.append(", ").append(version_);
        sb.append(", ").append(metaInfo_);
        sb.append(", ").append(deploymentId_);
        sb.append(", ").append(editorSourceValueId_);
        sb.append(", ").append(editorSourceExtraValueId_);
        sb.append(", ").append(tenantId_);

        sb.append(")");
        return sb.toString();
    }
}
