/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 流程模型设置表单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfForm implements Serializable {

    private static final long serialVersionUID = 1339484572;

    private String        id;
    private String        value;
    private String        type;
    private String        status;
    private String        nodeId;
    private String        mobileForm;
    private String        processModelId;
    private String        exprRule;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private String        nodeName;
    private String        nodeCode;
    private String        createBy;
    private String        updateBy;

    public BpmConfForm() {}

    public BpmConfForm(BpmConfForm value) {
        this.id = value.id;
        this.value = value.value;
        this.type = value.type;
        this.status = value.status;
        this.nodeId = value.nodeId;
        this.mobileForm = value.mobileForm;
        this.processModelId = value.processModelId;
        this.exprRule = value.exprRule;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.nodeName = value.nodeName;
        this.nodeCode = value.nodeCode;
        this.createBy = value.createBy;
        this.updateBy = value.updateBy;
    }

    public BpmConfForm(
        String        id,
        String        value,
        String        type,
        String        status,
        String        nodeId,
        String        mobileForm,
        String        processModelId,
        String        exprRule,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        String        nodeName,
        String        nodeCode,
        String        createBy,
        String        updateBy
    ) {
        this.id = id;
        this.value = value;
        this.type = type;
        this.status = status;
        this.nodeId = nodeId;
        this.mobileForm = mobileForm;
        this.processModelId = processModelId;
        this.exprRule = exprRule;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.nodeName = nodeName;
        this.nodeCode = nodeCode;
        this.createBy = createBy;
        this.updateBy = updateBy;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getNodeId() {
        return this.nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public String getMobileForm() {
        return this.mobileForm;
    }

    public void setMobileForm(String mobileForm) {
        this.mobileForm = mobileForm;
    }

    public String getProcessModelId() {
        return this.processModelId;
    }

    public void setProcessModelId(String processModelId) {
        this.processModelId = processModelId;
    }

    public String getExprRule() {
        return this.exprRule;
    }

    public void setExprRule(String exprRule) {
        this.exprRule = exprRule;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getNodeName() {
        return this.nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public String getNodeCode() {
        return this.nodeCode;
    }

    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BpmConfForm (");

        sb.append(id);
        sb.append(", ").append(value);
        sb.append(", ").append(type);
        sb.append(", ").append(status);
        sb.append(", ").append(nodeId);
        sb.append(", ").append(mobileForm);
        sb.append(", ").append(processModelId);
        sb.append(", ").append(exprRule);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(nodeName);
        sb.append(", ").append(nodeCode);
        sb.append(", ").append(createBy);
        sb.append(", ").append(updateBy);

        sb.append(")");
        return sb.toString();
    }
}
