/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfCountersign implements Serializable {

    private static final long serialVersionUID = 1489587911;

    private String id;
    private String sequential;
    private String participant;
    private String type;
    private String rate;
    private String nodeId;
    private String processModelId;
    private String status;
    private String nodeName;
    private String nodeCode;

    public BpmConfCountersign() {}

    public BpmConfCountersign(BpmConfCountersign value) {
        this.id = value.id;
        this.sequential = value.sequential;
        this.participant = value.participant;
        this.type = value.type;
        this.rate = value.rate;
        this.nodeId = value.nodeId;
        this.processModelId = value.processModelId;
        this.status = value.status;
        this.nodeName = value.nodeName;
        this.nodeCode = value.nodeCode;
    }

    public BpmConfCountersign(
        String id,
        String sequential,
        String participant,
        String type,
        String rate,
        String nodeId,
        String processModelId,
        String status,
        String nodeName,
        String nodeCode
    ) {
        this.id = id;
        this.sequential = sequential;
        this.participant = participant;
        this.type = type;
        this.rate = rate;
        this.nodeId = nodeId;
        this.processModelId = processModelId;
        this.status = status;
        this.nodeName = nodeName;
        this.nodeCode = nodeCode;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSequential() {
        return this.sequential;
    }

    public void setSequential(String sequential) {
        this.sequential = sequential;
    }

    public String getParticipant() {
        return this.participant;
    }

    public void setParticipant(String participant) {
        this.participant = participant;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRate() {
        return this.rate;
    }

    public void setRate(String rate) {
        this.rate = rate;
    }

    public String getNodeId() {
        return this.nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public String getProcessModelId() {
        return this.processModelId;
    }

    public void setProcessModelId(String processModelId) {
        this.processModelId = processModelId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getNodeName() {
        return this.nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public String getNodeCode() {
        return this.nodeCode;
    }

    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BpmConfCountersign (");

        sb.append(id);
        sb.append(", ").append(sequential);
        sb.append(", ").append(participant);
        sb.append(", ").append(type);
        sb.append(", ").append(rate);
        sb.append(", ").append(nodeId);
        sb.append(", ").append(processModelId);
        sb.append(", ").append(status);
        sb.append(", ").append(nodeName);
        sb.append(", ").append(nodeCode);

        sb.append(")");
        return sb.toString();
    }
}
