/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiVarinst;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiVarinstRecord extends UpdatableRecordImpl<ActHiVarinstRecord> implements Record14<String, String, String, String, String, String, Integer, String, Double, Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -742440923;

    /**
     * Setter for <code>workflow.act_hi_varinst.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.execution_id_</code>.
     */
    public void setExecutionId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.execution_id_</code>.
     */
    public String getExecutionId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.name_</code>.
     */
    public void setName_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.name_</code>.
     */
    public String getName_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.var_type_</code>.
     */
    public void setVarType_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.var_type_</code>.
     */
    public String getVarType_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.bytearray_id_</code>.
     */
    public void setBytearrayId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.bytearray_id_</code>.
     */
    public String getBytearrayId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.double_</code>.
     */
    public void setDouble_(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.double_</code>.
     */
    public Double getDouble_() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.long_</code>.
     */
    public void setLong_(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.long_</code>.
     */
    public Long getLong_() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.text_</code>.
     */
    public void setText_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.text_</code>.
     */
    public String getText_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.text2_</code>.
     */
    public void setText2_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.text2_</code>.
     */
    public String getText2_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.create_time_</code>.
     */
    public void setCreateTime_(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.create_time_</code>.
     */
    public LocalDateTime getCreateTime_() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>workflow.act_hi_varinst.last_updated_time_</code>.
     */
    public void setLastUpdatedTime_(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.act_hi_varinst.last_updated_time_</code>.
     */
    public LocalDateTime getLastUpdatedTime_() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, Integer, String, Double, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, Integer, String, Double, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ActHiVarinst.ACT_HI_VARINST.ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ActHiVarinst.ACT_HI_VARINST.PROC_INST_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ActHiVarinst.ACT_HI_VARINST.EXECUTION_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ActHiVarinst.ACT_HI_VARINST.TASK_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ActHiVarinst.ACT_HI_VARINST.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ActHiVarinst.ACT_HI_VARINST.VAR_TYPE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ActHiVarinst.ACT_HI_VARINST.REV_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ActHiVarinst.ACT_HI_VARINST.BYTEARRAY_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return ActHiVarinst.ACT_HI_VARINST.DOUBLE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return ActHiVarinst.ACT_HI_VARINST.LONG_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ActHiVarinst.ACT_HI_VARINST.TEXT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ActHiVarinst.ACT_HI_VARINST.TEXT2_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return ActHiVarinst.ACT_HI_VARINST.CREATE_TIME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return ActHiVarinst.ACT_HI_VARINST.LAST_UPDATED_TIME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProcInstId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExecutionId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTaskId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getVarType_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getRev_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBytearrayId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getDouble_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getLong_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getText_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getText2_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getCreateTime_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component14() {
        return getLastUpdatedTime_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProcInstId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExecutionId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTaskId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getVarType_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getRev_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBytearrayId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getDouble_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getLong_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getText_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getText2_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getCreateTime_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getLastUpdatedTime_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value1(String value) {
        setId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value2(String value) {
        setProcInstId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value3(String value) {
        setExecutionId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value4(String value) {
        setTaskId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value5(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value6(String value) {
        setVarType_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value7(Integer value) {
        setRev_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value8(String value) {
        setBytearrayId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value9(Double value) {
        setDouble_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value10(Long value) {
        setLong_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value11(String value) {
        setText_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value12(String value) {
        setText2_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value13(LocalDateTime value) {
        setCreateTime_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord value14(LocalDateTime value) {
        setLastUpdatedTime_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActHiVarinstRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8, Double value9, Long value10, String value11, String value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiVarinstRecord
     */
    public ActHiVarinstRecord() {
        super(ActHiVarinst.ACT_HI_VARINST);
    }

    /**
     * Create a detached, initialised ActHiVarinstRecord
     */
    public ActHiVarinstRecord(String id_, String procInstId_, String executionId_, String taskId_, String name_, String varType_, Integer rev_, String bytearrayId_, Double double_, Long long_, String text_, String text2_, LocalDateTime createTime_, LocalDateTime lastUpdatedTime_) {
        super(ActHiVarinst.ACT_HI_VARINST);

        set(0, id_);
        set(1, procInstId_);
        set(2, executionId_);
        set(3, taskId_);
        set(4, name_);
        set(5, varType_);
        set(6, rev_);
        set(7, bytearrayId_);
        set(8, double_);
        set(9, long_);
        set(10, text_);
        set(11, text2_);
        set(12, createTime_);
        set(13, lastUpdatedTime_);
    }
}
