/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.ActRuIntegration;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuIntegrationRecord extends UpdatableRecordImpl<ActRuIntegrationRecord> implements Record6<String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 320264261;

    /**
     * Setter for <code>workflow.act_ru_integration.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.act_ru_integration.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.act_ru_integration.execution_id_</code>.
     */
    public void setExecutionId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.act_ru_integration.execution_id_</code>.
     */
    public String getExecutionId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.act_ru_integration.process_instance_id_</code>.
     */
    public void setProcessInstanceId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.act_ru_integration.process_instance_id_</code>.
     */
    public String getProcessInstanceId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.act_ru_integration.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.act_ru_integration.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.act_ru_integration.flow_node_id_</code>.
     */
    public void setFlowNodeId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.act_ru_integration.flow_node_id_</code>.
     */
    public String getFlowNodeId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.act_ru_integration.created_date_</code>.
     */
    public void setCreatedDate_(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.act_ru_integration.created_date_</code>.
     */
    public LocalDateTime getCreatedDate_() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ActRuIntegration.ACT_RU_INTEGRATION.ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ActRuIntegration.ACT_RU_INTEGRATION.EXECUTION_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ActRuIntegration.ACT_RU_INTEGRATION.PROCESS_INSTANCE_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ActRuIntegration.ACT_RU_INTEGRATION.PROC_DEF_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ActRuIntegration.ACT_RU_INTEGRATION.FLOW_NODE_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return ActRuIntegration.ACT_RU_INTEGRATION.CREATED_DATE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExecutionId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProcessInstanceId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProcDefId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFlowNodeId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getCreatedDate_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExecutionId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProcessInstanceId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProcDefId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFlowNodeId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatedDate_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord value1(String value) {
        setId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord value2(String value) {
        setExecutionId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord value3(String value) {
        setProcessInstanceId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord value4(String value) {
        setProcDefId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord value5(String value) {
        setFlowNodeId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord value6(LocalDateTime value) {
        setCreatedDate_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActRuIntegrationRecord values(String value1, String value2, String value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActRuIntegrationRecord
     */
    public ActRuIntegrationRecord() {
        super(ActRuIntegration.ACT_RU_INTEGRATION);
    }

    /**
     * Create a detached, initialised ActRuIntegrationRecord
     */
    public ActRuIntegrationRecord(String id_, String executionId_, String processInstanceId_, String procDefId_, String flowNodeId_, LocalDateTime createdDate_) {
        super(ActRuIntegration.ACT_RU_INTEGRATION);

        set(0, id_);
        set(1, executionId_);
        set(2, processInstanceId_);
        set(3, procDefId_);
        set(4, flowNodeId_);
        set(5, createdDate_);
    }
}
