/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.ActReProcdef;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReProcdefRecord extends UpdatableRecordImpl<ActReProcdefRecord> implements Record16<String, Integer, String, String, String, Integer, String, String, String, String, Boolean, Boolean, Integer, String, String, Integer> {

    private static final long serialVersionUID = 13219242;

    /**
     * Setter for <code>workflow.act_re_procdef.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.category_</code>.
     */
    public void setCategory_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.category_</code>.
     */
    public String getCategory_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.name_</code>.
     */
    public void setName_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.name_</code>.
     */
    public String getName_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.key_</code>.
     */
    public void setKey_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.key_</code>.
     */
    public String getKey_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.version_</code>.
     */
    public void setVersion_(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.version_</code>.
     */
    public Integer getVersion_() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.deployment_id_</code>.
     */
    public void setDeploymentId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.deployment_id_</code>.
     */
    public String getDeploymentId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.resource_name_</code>.
     */
    public void setResourceName_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.resource_name_</code>.
     */
    public String getResourceName_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.dgrm_resource_name_</code>.
     */
    public void setDgrmResourceName_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.dgrm_resource_name_</code>.
     */
    public String getDgrmResourceName_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.description_</code>.
     */
    public void setDescription_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.description_</code>.
     */
    public String getDescription_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.has_start_form_key_</code>.
     */
    public void setHasStartFormKey_(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.has_start_form_key_</code>.
     */
    public Boolean getHasStartFormKey_() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.has_graphical_notation_</code>.
     */
    public void setHasGraphicalNotation_(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.has_graphical_notation_</code>.
     */
    public Boolean getHasGraphicalNotation_() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.suspension_state_</code>.
     */
    public void setSuspensionState_(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.suspension_state_</code>.
     */
    public Integer getSuspensionState_() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.engine_version_</code>.
     */
    public void setEngineVersion_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.engine_version_</code>.
     */
    public String getEngineVersion_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow.act_re_procdef.app_version_</code>.
     */
    public void setAppVersion_(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow.act_re_procdef.app_version_</code>.
     */
    public Integer getAppVersion_() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, Integer, String, String, String, Integer, String, String, String, String, Boolean, Boolean, Integer, String, String, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, Integer, String, String, String, Integer, String, String, String, String, Boolean, Boolean, Integer, String, String, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ActReProcdef.ACT_RE_PROCDEF.ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ActReProcdef.ACT_RE_PROCDEF.REV_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ActReProcdef.ACT_RE_PROCDEF.CATEGORY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ActReProcdef.ACT_RE_PROCDEF.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ActReProcdef.ACT_RE_PROCDEF.KEY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ActReProcdef.ACT_RE_PROCDEF.VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ActReProcdef.ACT_RE_PROCDEF.DEPLOYMENT_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ActReProcdef.ACT_RE_PROCDEF.RESOURCE_NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ActReProcdef.ACT_RE_PROCDEF.DGRM_RESOURCE_NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ActReProcdef.ACT_RE_PROCDEF.DESCRIPTION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return ActReProcdef.ACT_RE_PROCDEF.HAS_START_FORM_KEY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return ActReProcdef.ACT_RE_PROCDEF.HAS_GRAPHICAL_NOTATION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return ActReProcdef.ACT_RE_PROCDEF.SUSPENSION_STATE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return ActReProcdef.ACT_RE_PROCDEF.TENANT_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return ActReProcdef.ACT_RE_PROCDEF.ENGINE_VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return ActReProcdef.ACT_RE_PROCDEF.APP_VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRev_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCategory_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getKey_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDeploymentId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getResourceName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDgrmResourceName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDescription_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getHasStartFormKey_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getHasGraphicalNotation_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getSuspensionState_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getTenantId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getEngineVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getAppVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRev_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategory_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getKey_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDeploymentId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getResourceName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDgrmResourceName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDescription_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getHasStartFormKey_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getHasGraphicalNotation_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getSuspensionState_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getTenantId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getEngineVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getAppVersion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value1(String value) {
        setId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value3(String value) {
        setCategory_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value4(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value5(String value) {
        setKey_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value6(Integer value) {
        setVersion_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value7(String value) {
        setDeploymentId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value8(String value) {
        setResourceName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value9(String value) {
        setDgrmResourceName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value10(String value) {
        setDescription_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value11(Boolean value) {
        setHasStartFormKey_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value12(Boolean value) {
        setHasGraphicalNotation_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value13(Integer value) {
        setSuspensionState_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value14(String value) {
        setTenantId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value15(String value) {
        setEngineVersion_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord value16(Integer value) {
        setAppVersion_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReProcdefRecord values(String value1, Integer value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10, Boolean value11, Boolean value12, Integer value13, String value14, String value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActReProcdefRecord
     */
    public ActReProcdefRecord() {
        super(ActReProcdef.ACT_RE_PROCDEF);
    }

    /**
     * Create a detached, initialised ActReProcdefRecord
     */
    public ActReProcdefRecord(String id_, Integer rev_, String category_, String name_, String key_, Integer version_, String deploymentId_, String resourceName_, String dgrmResourceName_, String description_, Boolean hasStartFormKey_, Boolean hasGraphicalNotation_, Integer suspensionState_, String tenantId_, String engineVersion_, Integer appVersion_) {
        super(ActReProcdef.ACT_RE_PROCDEF);

        set(0, id_);
        set(1, rev_);
        set(2, category_);
        set(3, name_);
        set(4, key_);
        set(5, version_);
        set(6, deploymentId_);
        set(7, resourceName_);
        set(8, dgrmResourceName_);
        set(9, description_);
        set(10, hasStartFormKey_);
        set(11, hasGraphicalNotation_);
        set(12, suspensionState_);
        set(13, tenantId_);
        set(14, engineVersion_);
        set(15, appVersion_);
    }
}
