/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.BpmConfOperation;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfOperationRecord extends UpdatableRecordImpl<BpmConfOperationRecord> implements Record21<String, String, Integer, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1975602174;

    /**
     * Setter for <code>workflow.bpm_conf_operation.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.priority</code>.
     */
    public void setPriority(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.node_id</code>.
     */
    public void setNodeId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.node_id</code>.
     */
    public String getNodeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.process_model_id</code>.
     */
    public void setProcessModelId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.process_model_id</code>.
     */
    public String getProcessModelId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.flow_method</code>.
     */
    public void setFlowMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.flow_method</code>.
     */
    public String getFlowMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.op_jsname</code>.
     */
    public void setOpJsname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.op_jsname</code>.
     */
    public String getOpJsname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.op_url</code>.
     */
    public void setOpUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.op_url</code>.
     */
    public String getOpUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.op_expr</code>.
     */
    public void setOpExpr(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.op_expr</code>.
     */
    public String getOpExpr() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.btn_class</code>.
     */
    public void setBtnClass(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.btn_class</code>.
     */
    public String getBtnClass() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.opjs_param</code>.
     */
    public void setOpjsParam(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.opjs_param</code>.
     */
    public String getOpjsParam() {
        return (String) get(15);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.mop_jsname</code>.
     */
    public void setMopJsname(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.mop_jsname</code>.
     */
    public String getMopJsname() {
        return (String) get(16);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.mop_url</code>.
     */
    public void setMopUrl(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.mop_url</code>.
     */
    public String getMopUrl() {
        return (String) get(17);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.mop_class</code>.
     */
    public void setMopClass(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.mop_class</code>.
     */
    public String getMopClass() {
        return (String) get(18);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.node_name</code>.
     */
    public void setNodeName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(19);
    }

    /**
     * Setter for <code>workflow.bpm_conf_operation.node_code</code>.
     */
    public void setNodeCode(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_operation.node_code</code>.
     */
    public String getNodeCode() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<String, String, Integer, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<String, String, Integer, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BpmConfOperation.BPM_CONF_OPERATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BpmConfOperation.BPM_CONF_OPERATION.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return BpmConfOperation.BPM_CONF_OPERATION.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BpmConfOperation.BPM_CONF_OPERATION.NODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BpmConfOperation.BPM_CONF_OPERATION.PROCESS_MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BpmConfOperation.BPM_CONF_OPERATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BpmConfOperation.BPM_CONF_OPERATION.FLOW_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BpmConfOperation.BPM_CONF_OPERATION.OP_JSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BpmConfOperation.BPM_CONF_OPERATION.OP_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BpmConfOperation.BPM_CONF_OPERATION.OP_EXPR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return BpmConfOperation.BPM_CONF_OPERATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return BpmConfOperation.BPM_CONF_OPERATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return BpmConfOperation.BPM_CONF_OPERATION.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return BpmConfOperation.BPM_CONF_OPERATION.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return BpmConfOperation.BPM_CONF_OPERATION.BTN_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return BpmConfOperation.BPM_CONF_OPERATION.OPJS_PARAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return BpmConfOperation.BPM_CONF_OPERATION.MOP_JSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return BpmConfOperation.BPM_CONF_OPERATION.MOP_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return BpmConfOperation.BPM_CONF_OPERATION.MOP_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return BpmConfOperation.BPM_CONF_OPERATION.NODE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return BpmConfOperation.BPM_CONF_OPERATION.NODE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProcessModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFlowMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getOpJsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOpUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getOpExpr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getBtnClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getOpjsParam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getMopJsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getMopUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getMopClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component21() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProcessModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFlowMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getOpJsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOpUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getOpExpr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getBtnClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getOpjsParam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getMopJsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getMopUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getMopClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value3(Integer value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value4(String value) {
        setNodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value5(String value) {
        setProcessModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value7(String value) {
        setFlowMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value8(String value) {
        setOpJsname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value9(String value) {
        setOpUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value10(String value) {
        setOpExpr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value11(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value13(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value14(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value15(String value) {
        setBtnClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value16(String value) {
        setOpjsParam(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value17(String value) {
        setMopJsname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value18(String value) {
        setMopUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value19(String value) {
        setMopClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value20(String value) {
        setNodeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord value21(String value) {
        setNodeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperationRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20, String value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BpmConfOperationRecord
     */
    public BpmConfOperationRecord() {
        super(BpmConfOperation.BPM_CONF_OPERATION);
    }

    /**
     * Create a detached, initialised BpmConfOperationRecord
     */
    public BpmConfOperationRecord(String id, String value, Integer priority, String nodeId, String processModelId, String status, String flowMethod, String opJsname, String opUrl, String opExpr, LocalDateTime createTime, LocalDateTime updateTime, String createBy, String updateBy, String btnClass, String opjsParam, String mopJsname, String mopUrl, String mopClass, String nodeName, String nodeCode) {
        super(BpmConfOperation.BPM_CONF_OPERATION);

        set(0, id);
        set(1, value);
        set(2, priority);
        set(3, nodeId);
        set(4, processModelId);
        set(5, status);
        set(6, flowMethod);
        set(7, opJsname);
        set(8, opUrl);
        set(9, opExpr);
        set(10, createTime);
        set(11, updateTime);
        set(12, createBy);
        set(13, updateBy);
        set(14, btnClass);
        set(15, opjsParam);
        set(16, mopJsname);
        set(17, mopUrl);
        set(18, mopClass);
        set(19, nodeName);
        set(20, nodeCode);
    }
}
