/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.BpmConfNotice;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 流程模型设置通知
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfNoticeRecord extends UpdatableRecordImpl<BpmConfNoticeRecord> implements Record16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = -2114610821;

    /**
     * Setter for <code>workflow.bpm_conf_notice.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.receiver</code>.
     */
    public void setReceiver(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.receiver</code>.
     */
    public String getReceiver() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.due_date</code>.
     */
    public void setDueDate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.due_date</code>.
     */
    public String getDueDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.node_id</code>.
     */
    public void setNodeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.node_id</code>.
     */
    public String getNodeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.template_id</code>.
     */
    public void setTemplateId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.template_id</code>.
     */
    public String getTemplateId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.template_code</code>.
     */
    public void setTemplateCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.template_code</code>.
     */
    public String getTemplateCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.notification_type</code>.
     */
    public void setNotificationType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.notification_type</code>.
     */
    public String getNotificationType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.process_model_id</code>.
     */
    public void setProcessModelId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.process_model_id</code>.
     */
    public String getProcessModelId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.node_name</code>.
     */
    public void setNodeName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow.bpm_conf_notice.node_code</code>.
     */
    public void setNodeCode(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_notice.node_code</code>.
     */
    public String getNodeCode() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BpmConfNotice.BPM_CONF_NOTICE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BpmConfNotice.BPM_CONF_NOTICE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BpmConfNotice.BPM_CONF_NOTICE.RECEIVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BpmConfNotice.BPM_CONF_NOTICE.DUE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BpmConfNotice.BPM_CONF_NOTICE.NODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BpmConfNotice.BPM_CONF_NOTICE.TEMPLATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BpmConfNotice.BPM_CONF_NOTICE.TEMPLATE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BpmConfNotice.BPM_CONF_NOTICE.NOTIFICATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BpmConfNotice.BPM_CONF_NOTICE.PROCESS_MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BpmConfNotice.BPM_CONF_NOTICE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return BpmConfNotice.BPM_CONF_NOTICE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return BpmConfNotice.BPM_CONF_NOTICE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return BpmConfNotice.BPM_CONF_NOTICE.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return BpmConfNotice.BPM_CONF_NOTICE.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return BpmConfNotice.BPM_CONF_NOTICE.NODE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return BpmConfNotice.BPM_CONF_NOTICE.NODE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDueDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTemplateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTemplateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getProcessModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDueDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTemplateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTemplateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getProcessModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value2(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value3(String value) {
        setReceiver(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value4(String value) {
        setDueDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value5(String value) {
        setNodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value6(String value) {
        setTemplateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value7(String value) {
        setTemplateCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value8(String value) {
        setNotificationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value9(String value) {
        setProcessModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value10(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value11(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value13(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value14(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value15(String value) {
        setNodeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord value16(String value) {
        setNodeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfNoticeRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BpmConfNoticeRecord
     */
    public BpmConfNoticeRecord() {
        super(BpmConfNotice.BPM_CONF_NOTICE);
    }

    /**
     * Create a detached, initialised BpmConfNoticeRecord
     */
    public BpmConfNoticeRecord(String id, String type, String receiver, String dueDate, String nodeId, String templateId, String templateCode, String notificationType, String processModelId, String status, LocalDateTime createTime, LocalDateTime updateTime, String createBy, String updateBy, String nodeName, String nodeCode) {
        super(BpmConfNotice.BPM_CONF_NOTICE);

        set(0, id);
        set(1, type);
        set(2, receiver);
        set(3, dueDate);
        set(4, nodeId);
        set(5, templateId);
        set(6, templateCode);
        set(7, notificationType);
        set(8, processModelId);
        set(9, status);
        set(10, createTime);
        set(11, updateTime);
        set(12, createBy);
        set(13, updateBy);
        set(14, nodeName);
        set(15, nodeCode);
    }
}
