/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.BpmConfRule;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfRuleRecord extends UpdatableRecordImpl<BpmConfRuleRecord> implements Record11<String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = -1680243537;

    /**
     * Setter for <code>workflow.bpm_conf_rule.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.node_id</code>.
     */
    public void setNodeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.node_id</code>.
     */
    public String getNodeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.process_model_id</code>.
     */
    public void setProcessModelId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.process_model_id</code>.
     */
    public String getProcessModelId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.node_name</code>.
     */
    public void setNodeName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.bpm_conf_rule.node_code</code>.
     */
    public void setNodeCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.bpm_conf_rule.node_code</code>.
     */
    public String getNodeCode() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BpmConfRule.BPM_CONF_RULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BpmConfRule.BPM_CONF_RULE.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BpmConfRule.BPM_CONF_RULE.NODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BpmConfRule.BPM_CONF_RULE.PROCESS_MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BpmConfRule.BPM_CONF_RULE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return BpmConfRule.BPM_CONF_RULE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return BpmConfRule.BPM_CONF_RULE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BpmConfRule.BPM_CONF_RULE.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BpmConfRule.BPM_CONF_RULE.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BpmConfRule.BPM_CONF_RULE.NODE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return BpmConfRule.BPM_CONF_RULE.NODE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProcessModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProcessModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value3(String value) {
        setNodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value4(String value) {
        setProcessModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value7(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value8(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value9(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value10(String value) {
        setNodeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord value11(String value) {
        setNodeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfRuleRecord values(String value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BpmConfRuleRecord
     */
    public BpmConfRuleRecord() {
        super(BpmConfRule.BPM_CONF_RULE);
    }

    /**
     * Create a detached, initialised BpmConfRuleRecord
     */
    public BpmConfRuleRecord(String id, String value, String nodeId, String processModelId, String status, LocalDateTime createTime, LocalDateTime updateTime, String createBy, String updateBy, String nodeName, String nodeCode) {
        super(BpmConfRule.BPM_CONF_RULE);

        set(0, id);
        set(1, value);
        set(2, nodeId);
        set(3, processModelId);
        set(4, status);
        set(5, createTime);
        set(6, updateTime);
        set(7, createBy);
        set(8, updateBy);
        set(9, nodeName);
        set(10, nodeCode);
    }
}
