/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.TaskDefNotification;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskDefNotificationRecord extends UpdatableRecordImpl<TaskDefNotificationRecord> implements Record14<String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1221249285;

    /**
     * Setter for <code>workflow.task_def_notification.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.task_def_notification.event_name</code>.
     */
    public void setEventName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.event_name</code>.
     */
    public String getEventName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.task_def_notification.receiver</code>.
     */
    public void setReceiver(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.receiver</code>.
     */
    public String getReceiver() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.task_def_notification.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.task_def_notification.template_code</code>.
     */
    public void setTemplateCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.template_code</code>.
     */
    public String getTemplateCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.task_def_notification.base_id</code>.
     */
    public void setBaseId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.base_id</code>.
     */
    public String getBaseId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow.task_def_notification.process_definition_id</code>.
     */
    public void setProcessDefinitionId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.process_definition_id</code>.
     */
    public String getProcessDefinitionId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.task_def_notification.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.task_def_notification.node_code</code>.
     */
    public void setNodeCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.node_code</code>.
     */
    public String getNodeCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow.task_def_notification.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>workflow.task_def_notification.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>workflow.task_def_notification.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow.task_def_notification.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow.task_def_notification.node_name</code>.
     */
    public void setNodeName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.task_def_notification.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.EVENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.RECEIVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.TEMPLATE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.BASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.PROCESS_DEFINITION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.NODE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TaskDefNotification.TASK_DEF_NOTIFICATION.NODE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEventName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTemplateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getProcessDefinitionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEventName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTemplateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProcessDefinitionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNodeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getNodeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value2(String value) {
        setEventName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value3(String value) {
        setReceiver(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value5(String value) {
        setTemplateCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value6(String value) {
        setBaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value7(String value) {
        setProcessDefinitionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value8(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value9(String value) {
        setNodeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value11(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value12(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value13(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord value14(String value) {
        setNodeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskDefNotificationRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, LocalDateTime value10, LocalDateTime value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskDefNotificationRecord
     */
    public TaskDefNotificationRecord() {
        super(TaskDefNotification.TASK_DEF_NOTIFICATION);
    }

    /**
     * Create a detached, initialised TaskDefNotificationRecord
     */
    public TaskDefNotificationRecord(String id, String eventName, String receiver, String type, String templateCode, String baseId, String processDefinitionId, String status, String nodeCode, LocalDateTime createTime, LocalDateTime updateTime, String createBy, String updateBy, String nodeName) {
        super(TaskDefNotification.TASK_DEF_NOTIFICATION);

        set(0, id);
        set(1, eventName);
        set(2, receiver);
        set(3, type);
        set(4, templateCode);
        set(5, baseId);
        set(6, processDefinitionId);
        set(7, status);
        set(8, nodeCode);
        set(9, createTime);
        set(10, updateTime);
        set(11, createBy);
        set(12, updateBy);
        set(13, nodeName);
    }
}
