/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.records;


import cn.com.ho.workflow.infrastructure.db.tables.TPBaseBusiness;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPBaseBusinessRecord extends UpdatableRecordImpl<TPBaseBusinessRecord> implements Record16<String, String, String, String, String, String, String, String, LocalDateTime, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1067957737;

    /**
     * Setter for <code>workflow.t_p_base_business.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.remark</code>.
     */
    public void setRemark(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.remark</code>.
     */
    public String getRemark() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.is_claim</code>.
     */
    public void setIsClaim(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.is_claim</code>.
     */
    public String getIsClaim() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.proc_inst_id</code>.
     */
    public void setProcInstId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.proc_inst_id</code>.
     */
    public String getProcInstId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.bus_table</code>.
     */
    public void setBusTable(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.bus_table</code>.
     */
    public String getBusTable() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.priority</code>.
     */
    public void setPriority(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.priority</code>.
     */
    public String getPriority() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.submit_time</code>.
     */
    public void setSubmitTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.submit_time</code>.
     */
    public LocalDateTime getSubmitTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.submitter</code>.
     */
    public void setSubmitter(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.submitter</code>.
     */
    public String getSubmitter() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.module</code>.
     */
    public void setModule(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.module</code>.
     */
    public String getModule() {
        return (String) get(10);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.parent_id</code>.
     */
    public void setParentId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.parent_id</code>.
     */
    public String getParentId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.accept_user</code>.
     */
    public void setAcceptUser(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.accept_user</code>.
     */
    public String getAcceptUser() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.applicant</code>.
     */
    public void setApplicant(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.applicant</code>.
     */
    public String getApplicant() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.bus_dept</code>.
     */
    public void setBusDept(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.bus_dept</code>.
     */
    public String getBusDept() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow.t_p_base_business.submitter_en</code>.
     */
    public void setSubmitterEn(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow.t_p_base_business.submitter_en</code>.
     */
    public String getSubmitterEn() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, String, String, String, String, LocalDateTime, String, String, String, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, String, String, String, String, LocalDateTime, String, String, String, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.IS_CLAIM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.PROC_INST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.BUS_TABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.SUBMIT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.SUBMITTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.MODULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.ACCEPT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.APPLICANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.BUS_DEPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TPBaseBusiness.T_P_BASE_BUSINESS.SUBMITTER_EN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIsClaim();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getProcInstId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBusTable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getSubmitTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getSubmitter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getAcceptUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getApplicant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getBusDept();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getSubmitterEn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIsClaim();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProcInstId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBusTable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getSubmitTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSubmitter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getAcceptUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getApplicant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getBusDept();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getSubmitterEn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value3(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value5(String value) {
        setIsClaim(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value6(String value) {
        setProcInstId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value7(String value) {
        setBusTable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value8(String value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value9(LocalDateTime value) {
        setSubmitTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value10(String value) {
        setSubmitter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value11(String value) {
        setModule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value12(String value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value13(String value) {
        setAcceptUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value14(String value) {
        setApplicant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value15(String value) {
        setBusDept(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord value16(String value) {
        setSubmitterEn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPBaseBusinessRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPBaseBusinessRecord
     */
    public TPBaseBusinessRecord() {
        super(TPBaseBusiness.T_P_BASE_BUSINESS);
    }

    /**
     * Create a detached, initialised TPBaseBusinessRecord
     */
    public TPBaseBusinessRecord(String id, String title, String remark, String status, String isClaim, String procInstId, String busTable, String priority, LocalDateTime submitTime, String submitter, String module, String parentId, String acceptUser, String applicant, String busDept, String submitterEn) {
        super(TPBaseBusiness.T_P_BASE_BUSINESS);

        set(0, id);
        set(1, title);
        set(2, remark);
        set(3, status);
        set(4, isClaim);
        set(5, procInstId);
        set(6, busTable);
        set(7, priority);
        set(8, submitTime);
        set(9, submitter);
        set(10, module);
        set(11, parentId);
        set(12, acceptUser);
        set(13, applicant);
        set(14, busDept);
        set(15, submitterEn);
    }
}
