/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables;


import cn.com.ho.workflow.infrastructure.db.Indexes;
import cn.com.ho.workflow.infrastructure.db.Keys;
import cn.com.ho.workflow.infrastructure.db.Workflow;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActReModelRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReModel extends TableImpl<ActReModelRecord> {

    private static final long serialVersionUID = 754612773;

    /**
     * The reference instance of <code>workflow.act_re_model</code>
     */
    public static final ActReModel ACT_RE_MODEL = new ActReModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActReModelRecord> getRecordType() {
        return ActReModelRecord.class;
    }

    /**
     * The column <code>workflow.act_re_model.id_</code>.
     */
    public final TableField<ActReModelRecord, String> ID_ = createField("id_", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>workflow.act_re_model.rev_</code>.
     */
    public final TableField<ActReModelRecord, Integer> REV_ = createField("rev_", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>workflow.act_re_model.name_</code>.
     */
    public final TableField<ActReModelRecord, String> NAME_ = createField("name_", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>workflow.act_re_model.key_</code>.
     */
    public final TableField<ActReModelRecord, String> KEY_ = createField("key_", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>workflow.act_re_model.category_</code>.
     */
    public final TableField<ActReModelRecord, String> CATEGORY_ = createField("category_", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>workflow.act_re_model.create_time_</code>.
     */
    public final TableField<ActReModelRecord, LocalDateTime> CREATE_TIME_ = createField("create_time_", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>workflow.act_re_model.last_update_time_</code>.
     */
    public final TableField<ActReModelRecord, LocalDateTime> LAST_UPDATE_TIME_ = createField("last_update_time_", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>workflow.act_re_model.version_</code>.
     */
    public final TableField<ActReModelRecord, Integer> VERSION_ = createField("version_", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>workflow.act_re_model.meta_info_</code>.
     */
    public final TableField<ActReModelRecord, String> META_INFO_ = createField("meta_info_", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>workflow.act_re_model.deployment_id_</code>.
     */
    public final TableField<ActReModelRecord, String> DEPLOYMENT_ID_ = createField("deployment_id_", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>workflow.act_re_model.editor_source_value_id_</code>.
     */
    public final TableField<ActReModelRecord, String> EDITOR_SOURCE_VALUE_ID_ = createField("editor_source_value_id_", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>workflow.act_re_model.editor_source_extra_value_id_</code>.
     */
    public final TableField<ActReModelRecord, String> EDITOR_SOURCE_EXTRA_VALUE_ID_ = createField("editor_source_extra_value_id_", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>workflow.act_re_model.tenant_id_</code>.
     */
    public final TableField<ActReModelRecord, String> TENANT_ID_ = createField("tenant_id_", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>workflow.act_re_model</code> table reference
     */
    public ActReModel() {
        this(DSL.name("act_re_model"), null);
    }

    /**
     * Create an aliased <code>workflow.act_re_model</code> table reference
     */
    public ActReModel(String alias) {
        this(DSL.name(alias), ACT_RE_MODEL);
    }

    /**
     * Create an aliased <code>workflow.act_re_model</code> table reference
     */
    public ActReModel(Name alias) {
        this(alias, ACT_RE_MODEL);
    }

    private ActReModel(Name alias, Table<ActReModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActReModel(Name alias, Table<ActReModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActReModel(Table<O> child, ForeignKey<O, ActReModelRecord> key) {
        super(child, key, ACT_RE_MODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Workflow.WORKFLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_IDX_MODEL_DEPLOYMENT, Indexes.ACT_IDX_MODEL_SOURCE, Indexes.ACT_IDX_MODEL_SOURCE_EXTRA, Indexes.ACT_RE_MODEL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ActReModelRecord> getPrimaryKey() {
        return Keys.ACT_RE_MODEL_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ActReModelRecord>> getKeys() {
        return Arrays.<UniqueKey<ActReModelRecord>>asList(Keys.ACT_RE_MODEL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ActReModelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActReModelRecord, ?>>asList(Keys.ACT_RE_MODEL__ACT_FK_MODEL_DEPLOYMENT, Keys.ACT_RE_MODEL__ACT_FK_MODEL_SOURCE, Keys.ACT_RE_MODEL__ACT_FK_MODEL_SOURCE_EXTRA);
    }

    public ActReDeployment actReDeployment() {
        return new ActReDeployment(this, Keys.ACT_RE_MODEL__ACT_FK_MODEL_DEPLOYMENT);
    }

    public ActGeBytearray actReModel_ActFkModelSource() {
        return new ActGeBytearray(this, Keys.ACT_RE_MODEL__ACT_FK_MODEL_SOURCE);
    }

    public ActGeBytearray actReModel_ActFkModelSourceExtra() {
        return new ActGeBytearray(this, Keys.ACT_RE_MODEL__ACT_FK_MODEL_SOURCE_EXTRA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReModel as(String alias) {
        return new ActReModel(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActReModel as(Name alias) {
        return new ActReModel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReModel rename(String name) {
        return new ActReModel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReModel rename(Name name) {
        return new ActReModel(name, null);
    }
}
