/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables;


import cn.com.ho.workflow.infrastructure.db.Indexes;
import cn.com.ho.workflow.infrastructure.db.Keys;
import cn.com.ho.workflow.infrastructure.db.Workflow;
import cn.com.ho.workflow.infrastructure.db.tables.records.BpmConfOperationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfOperation extends TableImpl<BpmConfOperationRecord> {

    private static final long serialVersionUID = -19558898;

    /**
     * The reference instance of <code>workflow.bpm_conf_operation</code>
     */
    public static final BpmConfOperation BPM_CONF_OPERATION = new BpmConfOperation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BpmConfOperationRecord> getRecordType() {
        return BpmConfOperationRecord.class;
    }

    /**
     * The column <code>workflow.bpm_conf_operation.id</code>.
     */
    public final TableField<BpmConfOperationRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.value</code>.
     */
    public final TableField<BpmConfOperationRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.priority</code>.
     */
    public final TableField<BpmConfOperationRecord, Integer> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.node_id</code>.
     */
    public final TableField<BpmConfOperationRecord, String> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.process_model_id</code>.
     */
    public final TableField<BpmConfOperationRecord, String> PROCESS_MODEL_ID = createField("process_model_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.status</code>.
     */
    public final TableField<BpmConfOperationRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.flow_method</code>.
     */
    public final TableField<BpmConfOperationRecord, String> FLOW_METHOD = createField("flow_method", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.op_jsname</code>.
     */
    public final TableField<BpmConfOperationRecord, String> OP_JSNAME = createField("op_jsname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.op_url</code>.
     */
    public final TableField<BpmConfOperationRecord, String> OP_URL = createField("op_url", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.op_expr</code>.
     */
    public final TableField<BpmConfOperationRecord, String> OP_EXPR = createField("op_expr", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.create_time</code>.
     */
    public final TableField<BpmConfOperationRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.update_time</code>.
     */
    public final TableField<BpmConfOperationRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.create_by</code>.
     */
    public final TableField<BpmConfOperationRecord, String> CREATE_BY = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.update_by</code>.
     */
    public final TableField<BpmConfOperationRecord, String> UPDATE_BY = createField("update_by", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.btn_class</code>.
     */
    public final TableField<BpmConfOperationRecord, String> BTN_CLASS = createField("btn_class", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.opjs_param</code>.
     */
    public final TableField<BpmConfOperationRecord, String> OPJS_PARAM = createField("opjs_param", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.mop_jsname</code>.
     */
    public final TableField<BpmConfOperationRecord, String> MOP_JSNAME = createField("mop_jsname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.mop_url</code>.
     */
    public final TableField<BpmConfOperationRecord, String> MOP_URL = createField("mop_url", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.mop_class</code>.
     */
    public final TableField<BpmConfOperationRecord, String> MOP_CLASS = createField("mop_class", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.node_name</code>.
     */
    public final TableField<BpmConfOperationRecord, String> NODE_NAME = createField("node_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_operation.node_code</code>.
     */
    public final TableField<BpmConfOperationRecord, String> NODE_CODE = createField("node_code", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>workflow.bpm_conf_operation</code> table reference
     */
    public BpmConfOperation() {
        this(DSL.name("bpm_conf_operation"), null);
    }

    /**
     * Create an aliased <code>workflow.bpm_conf_operation</code> table reference
     */
    public BpmConfOperation(String alias) {
        this(DSL.name(alias), BPM_CONF_OPERATION);
    }

    /**
     * Create an aliased <code>workflow.bpm_conf_operation</code> table reference
     */
    public BpmConfOperation(Name alias) {
        this(alias, BPM_CONF_OPERATION);
    }

    private BpmConfOperation(Name alias, Table<BpmConfOperationRecord> aliased) {
        this(alias, aliased, null);
    }

    private BpmConfOperation(Name alias, Table<BpmConfOperationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BpmConfOperation(Table<O> child, ForeignKey<O, BpmConfOperationRecord> key) {
        super(child, key, BPM_CONF_OPERATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Workflow.WORKFLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BPM_CONF_OPERATION_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BpmConfOperationRecord> getPrimaryKey() {
        return Keys.SYNTHETIC_PK_BPM_CONF_OPERATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BpmConfOperationRecord>> getKeys() {
        return Arrays.<UniqueKey<BpmConfOperationRecord>>asList(Keys.BPM_CONF_OPERATION_PK, Keys.SYNTHETIC_PK_BPM_CONF_OPERATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperation as(String alias) {
        return new BpmConfOperation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfOperation as(Name alias) {
        return new BpmConfOperation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BpmConfOperation rename(String name) {
        return new BpmConfOperation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BpmConfOperation rename(Name name) {
        return new BpmConfOperation(name, null);
    }
}
