/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables;


import cn.com.ho.workflow.infrastructure.db.Indexes;
import cn.com.ho.workflow.infrastructure.db.Keys;
import cn.com.ho.workflow.infrastructure.db.Workflow;
import cn.com.ho.workflow.infrastructure.db.tables.records.BpmConfListenerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 流程模型设置监听器
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpmConfListener extends TableImpl<BpmConfListenerRecord> {

    private static final long serialVersionUID = -920523058;

    /**
     * The reference instance of <code>workflow.bpm_conf_listener</code>
     */
    public static final BpmConfListener BPM_CONF_LISTENER = new BpmConfListener();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BpmConfListenerRecord> getRecordType() {
        return BpmConfListenerRecord.class;
    }

    /**
     * The column <code>workflow.bpm_conf_listener.id</code>.
     */
    public final TableField<BpmConfListenerRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.value</code>.
     */
    public final TableField<BpmConfListenerRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.type</code>.
     */
    public final TableField<BpmConfListenerRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.status</code>.
     */
    public final TableField<BpmConfListenerRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.priority</code>.
     */
    public final TableField<BpmConfListenerRecord, Integer> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.node_id</code>.
     */
    public final TableField<BpmConfListenerRecord, String> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.process_model_id</code>.
     */
    public final TableField<BpmConfListenerRecord, String> PROCESS_MODEL_ID = createField("process_model_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.ext_status</code>.
     */
    public final TableField<BpmConfListenerRecord, Integer> EXT_STATUS = createField("ext_status", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.create_time</code>.
     */
    public final TableField<BpmConfListenerRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.update_time</code>.
     */
    public final TableField<BpmConfListenerRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.create_by</code>.
     */
    public final TableField<BpmConfListenerRecord, String> CREATE_BY = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.update_by</code>.
     */
    public final TableField<BpmConfListenerRecord, String> UPDATE_BY = createField("update_by", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.node_name</code>.
     */
    public final TableField<BpmConfListenerRecord, String> NODE_NAME = createField("node_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.node_code</code>.
     */
    public final TableField<BpmConfListenerRecord, String> NODE_CODE = createField("node_code", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>workflow.bpm_conf_listener.bean_name</code>.
     */
    public final TableField<BpmConfListenerRecord, String> BEAN_NAME = createField("bean_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>workflow.bpm_conf_listener</code> table reference
     */
    public BpmConfListener() {
        this(DSL.name("bpm_conf_listener"), null);
    }

    /**
     * Create an aliased <code>workflow.bpm_conf_listener</code> table reference
     */
    public BpmConfListener(String alias) {
        this(DSL.name(alias), BPM_CONF_LISTENER);
    }

    /**
     * Create an aliased <code>workflow.bpm_conf_listener</code> table reference
     */
    public BpmConfListener(Name alias) {
        this(alias, BPM_CONF_LISTENER);
    }

    private BpmConfListener(Name alias, Table<BpmConfListenerRecord> aliased) {
        this(alias, aliased, null);
    }

    private BpmConfListener(Name alias, Table<BpmConfListenerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("流程模型设置监听器"));
    }

    public <O extends Record> BpmConfListener(Table<O> child, ForeignKey<O, BpmConfListenerRecord> key) {
        super(child, key, BPM_CONF_LISTENER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Workflow.WORKFLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BPM_CONF_LISTENER_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BpmConfListenerRecord> getPrimaryKey() {
        return Keys.SYNTHETIC_PK_BPM_CONF_LISTENER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BpmConfListenerRecord>> getKeys() {
        return Arrays.<UniqueKey<BpmConfListenerRecord>>asList(Keys.BPM_CONF_LISTENER_PK, Keys.SYNTHETIC_PK_BPM_CONF_LISTENER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfListener as(String alias) {
        return new BpmConfListener(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BpmConfListener as(Name alias) {
        return new BpmConfListener(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BpmConfListener rename(String name) {
        return new BpmConfListener(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BpmConfListener rename(Name name) {
        return new BpmConfListener(name, null);
    }
}
