/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiVarinst;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActHiVarinstRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActHiVarinstDao extends DAOImpl<ActHiVarinstRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst, String> {

    /**
     * Create a new ActHiVarinstDao without any configuration
     */
    public ActHiVarinstDao() {
        super(ActHiVarinst.ACT_HI_VARINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst.class);
    }

    /**
     * Create a new ActHiVarinstDao with an attached configuration
     */
    @Autowired
    public ActHiVarinstDao(Configuration configuration) {
        super(ActHiVarinst.ACT_HI_VARINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchById_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst fetchOneById_(String value) {
        return fetchOne(ActHiVarinst.ACT_HI_VARINST.ID_, value);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByProcInstId_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.PROC_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByExecutionId_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>task_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByTaskId_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.TASK_ID_, values);
    }

    /**
     * Fetch records that have <code>name_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByName_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.NAME_, values);
    }

    /**
     * Fetch records that have <code>var_type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByVarType_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.VAR_TYPE_, values);
    }

    /**
     * Fetch records that have <code>rev_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByRev_(Integer... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.REV_, values);
    }

    /**
     * Fetch records that have <code>bytearray_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByBytearrayId_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.BYTEARRAY_ID_, values);
    }

    /**
     * Fetch records that have <code>double_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByDouble_(Double... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.DOUBLE_, values);
    }

    /**
     * Fetch records that have <code>long_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByLong_(Long... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.LONG_, values);
    }

    /**
     * Fetch records that have <code>text_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByText_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.TEXT_, values);
    }

    /**
     * Fetch records that have <code>text2_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByText2_(String... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.TEXT2_, values);
    }

    /**
     * Fetch records that have <code>create_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByCreateTime_(LocalDateTime... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.CREATE_TIME_, values);
    }

    /**
     * Fetch records that have <code>last_updated_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiVarinst> fetchByLastUpdatedTime_(LocalDateTime... values) {
        return fetch(ActHiVarinst.ACT_HI_VARINST.LAST_UPDATED_TIME_, values);
    }
}
