/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiProcinst;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActHiProcinstRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActHiProcinstDao extends DAOImpl<ActHiProcinstRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst, String> {

    /**
     * Create a new ActHiProcinstDao without any configuration
     */
    public ActHiProcinstDao() {
        super(ActHiProcinst.ACT_HI_PROCINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst.class);
    }

    /**
     * Create a new ActHiProcinstDao with an attached configuration
     */
    @Autowired
    public ActHiProcinstDao(Configuration configuration) {
        super(ActHiProcinst.ACT_HI_PROCINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchById_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst fetchOneById_(String value) {
        return fetchOne(ActHiProcinst.ACT_HI_PROCINST.ID_, value);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByProcInstId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.PROC_INST_ID_, values);
    }

    /**
     * Fetch a unique record that has <code>proc_inst_id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst fetchOneByProcInstId_(String value) {
        return fetchOne(ActHiProcinst.ACT_HI_PROCINST.PROC_INST_ID_, value);
    }

    /**
     * Fetch records that have <code>business_key_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByBusinessKey_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.BUSINESS_KEY_, values);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByProcDefId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.PROC_DEF_ID_, values);
    }

    /**
     * Fetch records that have <code>start_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByStartTime_(LocalDateTime... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.START_TIME_, values);
    }

    /**
     * Fetch records that have <code>end_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByEndTime_(LocalDateTime... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.END_TIME_, values);
    }

    /**
     * Fetch records that have <code>duration_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByDuration_(Long... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.DURATION_, values);
    }

    /**
     * Fetch records that have <code>start_user_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByStartUserId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.START_USER_ID_, values);
    }

    /**
     * Fetch records that have <code>start_act_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByStartActId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.START_ACT_ID_, values);
    }

    /**
     * Fetch records that have <code>end_act_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByEndActId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.END_ACT_ID_, values);
    }

    /**
     * Fetch records that have <code>super_process_instance_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchBySuperProcessInstanceId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.SUPER_PROCESS_INSTANCE_ID_, values);
    }

    /**
     * Fetch records that have <code>delete_reason_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByDeleteReason_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.DELETE_REASON_, values);
    }

    /**
     * Fetch records that have <code>tenant_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByTenantId_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.TENANT_ID_, values);
    }

    /**
     * Fetch records that have <code>name_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiProcinst> fetchByName_(String... values) {
        return fetch(ActHiProcinst.ACT_HI_PROCINST.NAME_, values);
    }
}
