/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiIdentitylink;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActHiIdentitylinkRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActHiIdentitylinkDao extends DAOImpl<ActHiIdentitylinkRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink, String> {

    /**
     * Create a new ActHiIdentitylinkDao without any configuration
     */
    public ActHiIdentitylinkDao() {
        super(ActHiIdentitylink.ACT_HI_IDENTITYLINK, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink.class);
    }

    /**
     * Create a new ActHiIdentitylinkDao with an attached configuration
     */
    @Autowired
    public ActHiIdentitylinkDao(Configuration configuration) {
        super(ActHiIdentitylink.ACT_HI_IDENTITYLINK, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink> fetchById_(String... values) {
        return fetch(ActHiIdentitylink.ACT_HI_IDENTITYLINK.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink fetchOneById_(String value) {
        return fetchOne(ActHiIdentitylink.ACT_HI_IDENTITYLINK.ID_, value);
    }

    /**
     * Fetch records that have <code>group_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink> fetchByGroupId_(String... values) {
        return fetch(ActHiIdentitylink.ACT_HI_IDENTITYLINK.GROUP_ID_, values);
    }

    /**
     * Fetch records that have <code>type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink> fetchByType_(String... values) {
        return fetch(ActHiIdentitylink.ACT_HI_IDENTITYLINK.TYPE_, values);
    }

    /**
     * Fetch records that have <code>user_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink> fetchByUserId_(String... values) {
        return fetch(ActHiIdentitylink.ACT_HI_IDENTITYLINK.USER_ID_, values);
    }

    /**
     * Fetch records that have <code>task_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink> fetchByTaskId_(String... values) {
        return fetch(ActHiIdentitylink.ACT_HI_IDENTITYLINK.TASK_ID_, values);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiIdentitylink> fetchByProcInstId_(String... values) {
        return fetch(ActHiIdentitylink.ACT_HI_IDENTITYLINK.PROC_INST_ID_, values);
    }
}
