/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiDetail;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActHiDetailRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActHiDetailDao extends DAOImpl<ActHiDetailRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail, String> {

    /**
     * Create a new ActHiDetailDao without any configuration
     */
    public ActHiDetailDao() {
        super(ActHiDetail.ACT_HI_DETAIL, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail.class);
    }

    /**
     * Create a new ActHiDetailDao with an attached configuration
     */
    @Autowired
    public ActHiDetailDao(Configuration configuration) {
        super(ActHiDetail.ACT_HI_DETAIL, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchById_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail fetchOneById_(String value) {
        return fetchOne(ActHiDetail.ACT_HI_DETAIL.ID_, value);
    }

    /**
     * Fetch records that have <code>type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByType_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.TYPE_, values);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByProcInstId_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.PROC_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByExecutionId_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>task_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByTaskId_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.TASK_ID_, values);
    }

    /**
     * Fetch records that have <code>act_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByActInstId_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.ACT_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>name_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByName_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.NAME_, values);
    }

    /**
     * Fetch records that have <code>var_type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByVarType_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.VAR_TYPE_, values);
    }

    /**
     * Fetch records that have <code>rev_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByRev_(Integer... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.REV_, values);
    }

    /**
     * Fetch records that have <code>time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByTime_(LocalDateTime... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.TIME_, values);
    }

    /**
     * Fetch records that have <code>bytearray_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByBytearrayId_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.BYTEARRAY_ID_, values);
    }

    /**
     * Fetch records that have <code>double_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByDouble_(Double... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.DOUBLE_, values);
    }

    /**
     * Fetch records that have <code>long_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByLong_(Long... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.LONG_, values);
    }

    /**
     * Fetch records that have <code>text_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByText_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.TEXT_, values);
    }

    /**
     * Fetch records that have <code>text2_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiDetail> fetchByText2_(String... values) {
        return fetch(ActHiDetail.ACT_HI_DETAIL.TEXT2_, values);
    }
}
