/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiActinst;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActHiActinstRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActHiActinstDao extends DAOImpl<ActHiActinstRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst, String> {

    /**
     * Create a new ActHiActinstDao without any configuration
     */
    public ActHiActinstDao() {
        super(ActHiActinst.ACT_HI_ACTINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst.class);
    }

    /**
     * Create a new ActHiActinstDao with an attached configuration
     */
    @Autowired
    public ActHiActinstDao(Configuration configuration) {
        super(ActHiActinst.ACT_HI_ACTINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchById_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst fetchOneById_(String value) {
        return fetchOne(ActHiActinst.ACT_HI_ACTINST.ID_, value);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByProcDefId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.PROC_DEF_ID_, values);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByProcInstId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.PROC_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByExecutionId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>act_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByActId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.ACT_ID_, values);
    }

    /**
     * Fetch records that have <code>task_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByTaskId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.TASK_ID_, values);
    }

    /**
     * Fetch records that have <code>call_proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByCallProcInstId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.CALL_PROC_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>act_name_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByActName_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.ACT_NAME_, values);
    }

    /**
     * Fetch records that have <code>act_type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByActType_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.ACT_TYPE_, values);
    }

    /**
     * Fetch records that have <code>assignee_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByAssignee_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.ASSIGNEE_, values);
    }

    /**
     * Fetch records that have <code>start_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByStartTime_(LocalDateTime... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.START_TIME_, values);
    }

    /**
     * Fetch records that have <code>end_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByEndTime_(LocalDateTime... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.END_TIME_, values);
    }

    /**
     * Fetch records that have <code>duration_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByDuration_(Long... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.DURATION_, values);
    }

    /**
     * Fetch records that have <code>delete_reason_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByDeleteReason_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.DELETE_REASON_, values);
    }

    /**
     * Fetch records that have <code>tenant_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiActinst> fetchByTenantId_(String... values) {
        return fetch(ActHiActinst.ACT_HI_ACTINST.TENANT_ID_, values);
    }
}
