/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActHiTaskinst;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActHiTaskinstRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActHiTaskinstDao extends DAOImpl<ActHiTaskinstRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst, String> {

    /**
     * Create a new ActHiTaskinstDao without any configuration
     */
    public ActHiTaskinstDao() {
        super(ActHiTaskinst.ACT_HI_TASKINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst.class);
    }

    /**
     * Create a new ActHiTaskinstDao with an attached configuration
     */
    @Autowired
    public ActHiTaskinstDao(Configuration configuration) {
        super(ActHiTaskinst.ACT_HI_TASKINST, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchById_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst fetchOneById_(String value) {
        return fetchOne(ActHiTaskinst.ACT_HI_TASKINST.ID_, value);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByProcDefId_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.PROC_DEF_ID_, values);
    }

    /**
     * Fetch records that have <code>task_def_key_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByTaskDefKey_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.TASK_DEF_KEY_, values);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByProcInstId_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.PROC_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByExecutionId_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>name_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByName_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.NAME_, values);
    }

    /**
     * Fetch records that have <code>parent_task_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByParentTaskId_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.PARENT_TASK_ID_, values);
    }

    /**
     * Fetch records that have <code>description_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByDescription_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.DESCRIPTION_, values);
    }

    /**
     * Fetch records that have <code>owner_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByOwner_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.OWNER_, values);
    }

    /**
     * Fetch records that have <code>assignee_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByAssignee_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.ASSIGNEE_, values);
    }

    /**
     * Fetch records that have <code>start_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByStartTime_(LocalDateTime... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.START_TIME_, values);
    }

    /**
     * Fetch records that have <code>claim_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByClaimTime_(LocalDateTime... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.CLAIM_TIME_, values);
    }

    /**
     * Fetch records that have <code>end_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByEndTime_(LocalDateTime... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.END_TIME_, values);
    }

    /**
     * Fetch records that have <code>duration_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByDuration_(Long... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.DURATION_, values);
    }

    /**
     * Fetch records that have <code>delete_reason_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByDeleteReason_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.DELETE_REASON_, values);
    }

    /**
     * Fetch records that have <code>priority_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByPriority_(Integer... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.PRIORITY_, values);
    }

    /**
     * Fetch records that have <code>due_date_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByDueDate_(LocalDateTime... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.DUE_DATE_, values);
    }

    /**
     * Fetch records that have <code>form_key_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByFormKey_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.FORM_KEY_, values);
    }

    /**
     * Fetch records that have <code>category_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByCategory_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.CATEGORY_, values);
    }

    /**
     * Fetch records that have <code>tenant_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActHiTaskinst> fetchByTenantId_(String... values) {
        return fetch(ActHiTaskinst.ACT_HI_TASKINST.TENANT_ID_, values);
    }
}
