/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActProcdefInfo;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActProcdefInfoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActProcdefInfoDao extends DAOImpl<ActProcdefInfoRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo, String> {

    /**
     * Create a new ActProcdefInfoDao without any configuration
     */
    public ActProcdefInfoDao() {
        super(ActProcdefInfo.ACT_PROCDEF_INFO, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo.class);
    }

    /**
     * Create a new ActProcdefInfoDao with an attached configuration
     */
    @Autowired
    public ActProcdefInfoDao(Configuration configuration) {
        super(ActProcdefInfo.ACT_PROCDEF_INFO, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo> fetchById_(String... values) {
        return fetch(ActProcdefInfo.ACT_PROCDEF_INFO.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo fetchOneById_(String value) {
        return fetchOne(ActProcdefInfo.ACT_PROCDEF_INFO.ID_, value);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo> fetchByProcDefId_(String... values) {
        return fetch(ActProcdefInfo.ACT_PROCDEF_INFO.PROC_DEF_ID_, values);
    }

    /**
     * Fetch a unique record that has <code>proc_def_id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo fetchOneByProcDefId_(String value) {
        return fetchOne(ActProcdefInfo.ACT_PROCDEF_INFO.PROC_DEF_ID_, value);
    }

    /**
     * Fetch records that have <code>rev_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo> fetchByRev_(Integer... values) {
        return fetch(ActProcdefInfo.ACT_PROCDEF_INFO.REV_, values);
    }

    /**
     * Fetch records that have <code>info_json_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActProcdefInfo> fetchByInfoJsonId_(String... values) {
        return fetch(ActProcdefInfo.ACT_PROCDEF_INFO.INFO_JSON_ID_, values);
    }
}
