/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActRuVariable;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActRuVariableRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActRuVariableDao extends DAOImpl<ActRuVariableRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable, String> {

    /**
     * Create a new ActRuVariableDao without any configuration
     */
    public ActRuVariableDao() {
        super(ActRuVariable.ACT_RU_VARIABLE, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable.class);
    }

    /**
     * Create a new ActRuVariableDao with an attached configuration
     */
    @Autowired
    public ActRuVariableDao(Configuration configuration) {
        super(ActRuVariable.ACT_RU_VARIABLE, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchById_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable fetchOneById_(String value) {
        return fetchOne(ActRuVariable.ACT_RU_VARIABLE.ID_, value);
    }

    /**
     * Fetch records that have <code>rev_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByRev_(Integer... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.REV_, values);
    }

    /**
     * Fetch records that have <code>type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByType_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.TYPE_, values);
    }

    /**
     * Fetch records that have <code>name_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByName_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.NAME_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByExecutionId_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>proc_inst_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByProcInstId_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.PROC_INST_ID_, values);
    }

    /**
     * Fetch records that have <code>task_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByTaskId_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.TASK_ID_, values);
    }

    /**
     * Fetch records that have <code>bytearray_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByBytearrayId_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.BYTEARRAY_ID_, values);
    }

    /**
     * Fetch records that have <code>double_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByDouble_(Double... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.DOUBLE_, values);
    }

    /**
     * Fetch records that have <code>long_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByLong_(Long... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.LONG_, values);
    }

    /**
     * Fetch records that have <code>text_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByText_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.TEXT_, values);
    }

    /**
     * Fetch records that have <code>text2_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuVariable> fetchByText2_(String... values) {
        return fetch(ActRuVariable.ACT_RU_VARIABLE.TEXT2_, values);
    }
}
