/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActRuJob;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActRuJobRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActRuJobDao extends DAOImpl<ActRuJobRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob, String> {

    /**
     * Create a new ActRuJobDao without any configuration
     */
    public ActRuJobDao() {
        super(ActRuJob.ACT_RU_JOB, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob.class);
    }

    /**
     * Create a new ActRuJobDao with an attached configuration
     */
    @Autowired
    public ActRuJobDao(Configuration configuration) {
        super(ActRuJob.ACT_RU_JOB, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchById_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob fetchOneById_(String value) {
        return fetchOne(ActRuJob.ACT_RU_JOB.ID_, value);
    }

    /**
     * Fetch records that have <code>rev_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByRev_(Integer... values) {
        return fetch(ActRuJob.ACT_RU_JOB.REV_, values);
    }

    /**
     * Fetch records that have <code>type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByType_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.TYPE_, values);
    }

    /**
     * Fetch records that have <code>lock_exp_time_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByLockExpTime_(LocalDateTime... values) {
        return fetch(ActRuJob.ACT_RU_JOB.LOCK_EXP_TIME_, values);
    }

    /**
     * Fetch records that have <code>lock_owner_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByLockOwner_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.LOCK_OWNER_, values);
    }

    /**
     * Fetch records that have <code>exclusive_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByExclusive_(Boolean... values) {
        return fetch(ActRuJob.ACT_RU_JOB.EXCLUSIVE_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByExecutionId_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>process_instance_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByProcessInstanceId_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.PROCESS_INSTANCE_ID_, values);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByProcDefId_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.PROC_DEF_ID_, values);
    }

    /**
     * Fetch records that have <code>retries_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByRetries_(Integer... values) {
        return fetch(ActRuJob.ACT_RU_JOB.RETRIES_, values);
    }

    /**
     * Fetch records that have <code>exception_stack_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByExceptionStackId_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.EXCEPTION_STACK_ID_, values);
    }

    /**
     * Fetch records that have <code>exception_msg_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByExceptionMsg_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.EXCEPTION_MSG_, values);
    }

    /**
     * Fetch records that have <code>duedate_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByDuedate_(LocalDateTime... values) {
        return fetch(ActRuJob.ACT_RU_JOB.DUEDATE_, values);
    }

    /**
     * Fetch records that have <code>repeat_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByRepeat_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.REPEAT_, values);
    }

    /**
     * Fetch records that have <code>handler_type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByHandlerType_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.HANDLER_TYPE_, values);
    }

    /**
     * Fetch records that have <code>handler_cfg_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByHandlerCfg_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.HANDLER_CFG_, values);
    }

    /**
     * Fetch records that have <code>tenant_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuJob> fetchByTenantId_(String... values) {
        return fetch(ActRuJob.ACT_RU_JOB.TENANT_ID_, values);
    }
}
