/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActRuSuspendedJob;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActRuSuspendedJobRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActRuSuspendedJobDao extends DAOImpl<ActRuSuspendedJobRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob, String> {

    /**
     * Create a new ActRuSuspendedJobDao without any configuration
     */
    public ActRuSuspendedJobDao() {
        super(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob.class);
    }

    /**
     * Create a new ActRuSuspendedJobDao with an attached configuration
     */
    @Autowired
    public ActRuSuspendedJobDao(Configuration configuration) {
        super(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchById_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob fetchOneById_(String value) {
        return fetchOne(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.ID_, value);
    }

    /**
     * Fetch records that have <code>rev_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByRev_(Integer... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.REV_, values);
    }

    /**
     * Fetch records that have <code>type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByType_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.TYPE_, values);
    }

    /**
     * Fetch records that have <code>exclusive_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByExclusive_(Boolean... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.EXCLUSIVE_, values);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByExecutionId_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>process_instance_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByProcessInstanceId_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.PROCESS_INSTANCE_ID_, values);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByProcDefId_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.PROC_DEF_ID_, values);
    }

    /**
     * Fetch records that have <code>retries_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByRetries_(Integer... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.RETRIES_, values);
    }

    /**
     * Fetch records that have <code>exception_stack_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByExceptionStackId_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.EXCEPTION_STACK_ID_, values);
    }

    /**
     * Fetch records that have <code>exception_msg_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByExceptionMsg_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.EXCEPTION_MSG_, values);
    }

    /**
     * Fetch records that have <code>duedate_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByDuedate_(LocalDateTime... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.DUEDATE_, values);
    }

    /**
     * Fetch records that have <code>repeat_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByRepeat_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.REPEAT_, values);
    }

    /**
     * Fetch records that have <code>handler_type_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByHandlerType_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.HANDLER_TYPE_, values);
    }

    /**
     * Fetch records that have <code>handler_cfg_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByHandlerCfg_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.HANDLER_CFG_, values);
    }

    /**
     * Fetch records that have <code>tenant_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuSuspendedJob> fetchByTenantId_(String... values) {
        return fetch(ActRuSuspendedJob.ACT_RU_SUSPENDED_JOB.TENANT_ID_, values);
    }
}
