/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.ActRuIntegration;
import cn.com.ho.workflow.infrastructure.db.tables.records.ActRuIntegrationRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActRuIntegrationDao extends DAOImpl<ActRuIntegrationRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration, String> {

    /**
     * Create a new ActRuIntegrationDao without any configuration
     */
    public ActRuIntegrationDao() {
        super(ActRuIntegration.ACT_RU_INTEGRATION, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration.class);
    }

    /**
     * Create a new ActRuIntegrationDao with an attached configuration
     */
    @Autowired
    public ActRuIntegrationDao(Configuration configuration) {
        super(ActRuIntegration.ACT_RU_INTEGRATION, cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration> fetchById_(String... values) {
        return fetch(ActRuIntegration.ACT_RU_INTEGRATION.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration fetchOneById_(String value) {
        return fetchOne(ActRuIntegration.ACT_RU_INTEGRATION.ID_, value);
    }

    /**
     * Fetch records that have <code>execution_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration> fetchByExecutionId_(String... values) {
        return fetch(ActRuIntegration.ACT_RU_INTEGRATION.EXECUTION_ID_, values);
    }

    /**
     * Fetch records that have <code>process_instance_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration> fetchByProcessInstanceId_(String... values) {
        return fetch(ActRuIntegration.ACT_RU_INTEGRATION.PROCESS_INSTANCE_ID_, values);
    }

    /**
     * Fetch records that have <code>proc_def_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration> fetchByProcDefId_(String... values) {
        return fetch(ActRuIntegration.ACT_RU_INTEGRATION.PROC_DEF_ID_, values);
    }

    /**
     * Fetch records that have <code>flow_node_id_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration> fetchByFlowNodeId_(String... values) {
        return fetch(ActRuIntegration.ACT_RU_INTEGRATION.FLOW_NODE_ID_, values);
    }

    /**
     * Fetch records that have <code>created_date_ IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.ActRuIntegration> fetchByCreatedDate_(LocalDateTime... values) {
        return fetch(ActRuIntegration.ACT_RU_INTEGRATION.CREATED_DATE_, values);
    }
}
