/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.BpmConfListener;
import cn.com.ho.workflow.infrastructure.db.tables.records.BpmConfListenerRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 流程模型设置监听器
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class BpmConfListenerDao extends DAOImpl<BpmConfListenerRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener, String> {

    /**
     * Create a new BpmConfListenerDao without any configuration
     */
    public BpmConfListenerDao() {
        super(BpmConfListener.BPM_CONF_LISTENER, cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener.class);
    }

    /**
     * Create a new BpmConfListenerDao with an attached configuration
     */
    @Autowired
    public BpmConfListenerDao(Configuration configuration) {
        super(BpmConfListener.BPM_CONF_LISTENER, cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchById(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener fetchOneById(String value) {
        return fetchOne(BpmConfListener.BPM_CONF_LISTENER.ID, value);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByValue(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.VALUE, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByType(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.TYPE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByStatus(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.STATUS, values);
    }

    /**
     * Fetch records that have <code>priority IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByPriority(Integer... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.PRIORITY, values);
    }

    /**
     * Fetch records that have <code>node_id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByNodeId(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.NODE_ID, values);
    }

    /**
     * Fetch records that have <code>process_model_id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByProcessModelId(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.PROCESS_MODEL_ID, values);
    }

    /**
     * Fetch records that have <code>ext_status IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByExtStatus(Integer... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.EXT_STATUS, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByCreateTime(LocalDateTime... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByCreateBy(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByUpdateBy(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>node_name IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByNodeName(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.NODE_NAME, values);
    }

    /**
     * Fetch records that have <code>node_code IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByNodeCode(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.NODE_CODE, values);
    }

    /**
     * Fetch records that have <code>bean_name IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.BpmConfListener> fetchByBeanName(String... values) {
        return fetch(BpmConfListener.BPM_CONF_LISTENER.BEAN_NAME, values);
    }
}
