/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.TaskDefRule;
import cn.com.ho.workflow.infrastructure.db.tables.records.TaskDefRuleRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TaskDefRuleDao extends DAOImpl<TaskDefRuleRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule, String> {

    /**
     * Create a new TaskDefRuleDao without any configuration
     */
    public TaskDefRuleDao() {
        super(TaskDefRule.TASK_DEF_RULE, cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule.class);
    }

    /**
     * Create a new TaskDefRuleDao with an attached configuration
     */
    @Autowired
    public TaskDefRuleDao(Configuration configuration) {
        super(TaskDefRule.TASK_DEF_RULE, cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchById(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule fetchOneById(String value) {
        return fetchOne(TaskDefRule.TASK_DEF_RULE.ID, value);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByValue(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.VALUE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByStatus(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.STATUS, values);
    }

    /**
     * Fetch records that have <code>node_code IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByNodeCode(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.NODE_CODE, values);
    }

    /**
     * Fetch records that have <code>process_definition_id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByProcessDefinitionId(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.PROCESS_DEFINITION_ID, values);
    }

    /**
     * Fetch records that have <code>base_id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByBaseId(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.BASE_ID, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByCreateTime(LocalDateTime... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByCreateBy(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByUpdateBy(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>node_name IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefRule> fetchByNodeName(String... values) {
        return fetch(TaskDefRule.TASK_DEF_RULE.NODE_NAME, values);
    }
}
