/*
 * This file is generated by jOOQ.
 */
package cn.com.ho.workflow.infrastructure.db.tables.daos;


import cn.com.ho.workflow.infrastructure.db.tables.TaskDefBase;
import cn.com.ho.workflow.infrastructure.db.tables.records.TaskDefBaseRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TaskDefBaseDao extends DAOImpl<TaskDefBaseRecord, cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase, String> {

    /**
     * Create a new TaskDefBaseDao without any configuration
     */
    public TaskDefBaseDao() {
        super(TaskDefBase.TASK_DEF_BASE, cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase.class);
    }

    /**
     * Create a new TaskDefBaseDao with an attached configuration
     */
    @Autowired
    public TaskDefBaseDao(Configuration configuration) {
        super(TaskDefBase.TASK_DEF_BASE, cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchById(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase fetchOneById(String value) {
        return fetchOne(TaskDefBase.TASK_DEF_BASE.ID, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCode(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.CODE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByName(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.NAME, values);
    }

    /**
     * Fetch records that have <code>process_definition_id IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByProcessDefinitionId(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.PROCESS_DEFINITION_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByStatus(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.STATUS, values);
    }

    /**
     * Fetch records that have <code>skip IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchBySkip(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.SKIP, values);
    }

    /**
     * Fetch records that have <code>countersign_rate IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCountersignRate(Integer... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.COUNTERSIGN_RATE, values);
    }

    /**
     * Fetch records that have <code>countersign_strategy IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCountersignStrategy(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.COUNTERSIGN_STRATEGY, values);
    }

    /**
     * Fetch records that have <code>countersign_user IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCountersignUser(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.COUNTERSIGN_USER, values);
    }

    /**
     * Fetch records that have <code>countersign_type IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCountersignType(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.COUNTERSIGN_TYPE, values);
    }

    /**
     * Fetch records that have <code>assign_strategy IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByAssignStrategy(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.ASSIGN_STRATEGY, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCreateTime(LocalDateTime... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByCreateBy(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByUpdateBy(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>use_dept_role IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByUseDeptRole(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.USE_DEPT_ROLE, values);
    }

    /**
     * Fetch records that have <code>grab_order IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchByGrabOrder(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.GRAB_ORDER, values);
    }

    /**
     * Fetch records that have <code>skip_node_expr IN (values)</code>
     */
    public List<cn.com.ho.workflow.infrastructure.db.tables.pojos.TaskDefBase> fetchBySkipNodeExpr(String... values) {
        return fetch(TaskDefBase.TASK_DEF_BASE.SKIP_NODE_EXPR, values);
    }
}
